✨feat: Header 개선 작업 완료
NINI-Bros/GENISISU pull request #73
Opened 2024-10-21 09:40 UTC by ryungom

## ✍️ PR 한 줄 요약
#72 
Header 개선 작업 완료

## ✏ 상세 작업 내용

- (web) 브라우저에서 현재 페이지 표기
  - 활성화시 적용되는 font color white값이 살짝 눈에 띄지 않아서, 활성화시 weight를 500 부여. (semi-bold) 
  - ![241021_gnb활성화](https://github.com/user-attachments/assets/d6abb5c5-5161-4e97-9892-e5151f4bc31f)
  - 특정 클래스를 부여하여 split 하여 남은 문자열을 추출하고 해당 페이지의 pathname과 비교하여 조건문 넣던 것을 href 값을 호출하여 따로 클래스를 부여하지 않아도 현재 페이지 표기될 수 있도록 조건문 수정
- (mobile) 하단 GNB 투명으로 나타나는 이슈 -> dvh 값으로 위치 조정해주고 mobile GNB 기준 헤더 컴포넌트 자체에 배경색 지정 완료
- (mobile) input 입력값으로 가상키보드가 올라올 경우 하단 GNB 사라지도록 작업.
  - 전체 ui를 포함한 outerHeight 기준 60% (약 70vh) 보다 현재 브라우저 height인 innerHeight가 작아지면 Header 컴포넌트가 사라지도록 작업
  -  ![241021_하단gnb사라져줄게_1](https://github.com/user-attachments/assets/6cc7d244-e843-45ca-b08b-714f1e548819)

## ✅ PR 양식 체크리스트
 - [x] 💭 이슈는 등록했나요?
 - [x] 🏷️ 라벨은 등록했나요?
 - [x] 🔀 PR 제목의 형식을 잘 작성했나요?

2024-10-22 07:18 UTC, redcontroller requested changes
리액트에서 querySelector 로 요소의 속성을 변경하는 부분만 수정 요청 드릴게요!
헤더가 개선되서 훨씬 사용자 경험이 향상되어 기쁩니다 🤗👍

2024-10-22 07:18 UTC, redcontroller commented on src/app/css/basic_mediaQuery_950.css
> +    grid-template-rows: 0px minmax(calc(100dvh - 410px), auto) auto;
모바일에서 사용하면 좋은 새로운 단위를 저도 알게 되어 좋네요 🤗🙌

2024-10-22 07:18 UTC, redcontroller commented on src/components/layout/Header.tsx
> +    return () => window.removeEventListener('resize', thisHeight);
사용자가 입력을 할 때, 모바일 상에 GNB가 사라지면서 컨텐츠가 보이는 화면을 최대한 확보하게 되어 좋습니다! 👍👍👍

2024-10-22 07:18 UTC, redcontroller commented on src/components/layout/Header.tsx
> +      if (item.getAttribute('href')?.split('/')[1] === thisPath) {
querySelector를 사용해서 직접 DOM을 조작하는 방식은 React스럽지 않는 것 같습니다. 😥
아래 함수를 통해서 className 에 클래스를 추가하는 방식은 어떨까요? 🤔
```jsx
const isHere = (key) => key === pathName.split('/')[1] ? 'on' : '';
...
return (
    ....
    <Link href="/models" className=`${isHere('models')}`>
    ...
```

2024-10-23 05:33 UTC, ryungom commented on src/app/css/basic_mediaQuery_950.css
> +    grid-template-rows: 0px minmax(calc(100dvh - 410px), auto) auto;
네 저도 이번에 새로운 단위를 알게되어서 좋습니다. 배포환경에서도 생각한대로 잘 이루어지면 좋겠네요 😆

2024-10-23 05:34 UTC, ryungom commented on src/components/layout/Header.tsx
> +    return () => window.removeEventListener('resize', thisHeight);
모건님덕에 새로운 사고의전환을 할 수 있어서 편리했습니다. 모건님의 유연한 사고방식 정말 많이 배워야할점 같습니다.

2024-10-23 05:56 UTC, ryungom commented on src/components/layout/Header.tsx
> +      if (item.getAttribute('href')?.split('/')[1] === thisPath) {
코드 보시면 아시겠지만, 이 부분에서 querySelector는 ref로 가져온 부모요소의 DOM에서 검색하는 것이고, useEffect 안에서 마운트시 의존성 배열을 추적하면서 랜더링되고 ref 자체는 리액트 생명주기랑은 별개로 동작하기 때문에 React스럽지 않은것 같다는점은 저랑 의견이 좀 다른것 같습니다. 리액트의 가상 DOM과도 랜더링시 충돌이 나지 않도록 useEffect안에서 조작하고 있기 때문에 코드를 사용하는 방향이 다를지언정 '틀린' 부분이라고는 생각하지 않습니다.

다만 모건님이 제안해주신 코드 방식이 제가 쓴 방식보다 훨씬 간결하고 더욱 직관적인것으로 파악되어서 해당방법으로 고쳐보도록 하겠습니다. 좋은의견 감사드립니다 😃

2024-10-23 06:09 UTC, ryungom commented on src/components/layout/Header.tsx
> +      if (item.getAttribute('href')?.split('/')[1] === thisPath) {
흠 그런데... 코드를 수정하려고 다시 보니까 모건님께서 제안하신 방법을 쓴다면, Link가 추가될때마다 저 isHere 함수를 같이 넣어줘야 합니다.  직관적인 코드이긴 하지만 제가 쓴 방식으로 한다면 추후 Link가 추가될 경우 필수요소인 라우트 경로(href)만 추가된다면 추가 코드 조작 없이 잘 작동하게끔 하는 코드입니다. 현재 GNB 메뉴자체가 반복문으로 표출되는것도 아니라 일일히 지정해줘야 하고 모든 Link 태그에 해당 함수를 똑같이 넣어줘야 하는 작업이 생기기 때문에... 모건님께서 제 의견에 납득하신다면 이 부분은 굳이 고치지 않아 보려고 합니다. 한번 보시고 의견 달아주시거나, 디스코드에서 같이 이야기 나눠보아요.

2024-10-23 07:34 UTC, redcontroller commented on src/components/layout/Header.tsx
> +      if (item.getAttribute('href')?.split('/')[1] === thisPath) {
먼저 눈에 들어오는 부분부터 의견드릴게요.

**(1) ref로 잡은 부모요소 안에서 검색용도로 querySelector를 사용하는것**
querySelectorAll이라는 DOM 메서드를 사용해서 조건에 따라 DOM 요소의 클래스를 변경하고 있습니다.
그것이 DOM 조작이라고 말씀드린 겁니다.

**(2) Link가 추가될 때마다 저 isHere 함수를 같이 넣어줘야 합니다.** 
맞는 말씀입니다. 하지만 아래와 같이 간단한 구조라면 반복문으로 처리할 수 있어서 문제가 안된다고 생각합니다.
Link 태그에 들어갈 정보를 객체로 만들고 text와 href를 넣어주면 반복문을 만들 수 있을 것 같네요.
이때 isHere를 넣어주면 될 것 같네요. 
(isHere 함수가 state 없어서 렌더링할 때 반영이 안된다면 useEffect랑 useState를 추가로 써줘야 할 것 같아요)
```
    <li>
      <Link href="/models">모델</Link>
    </li>
    <li>
      <Link href="/drive">전시시승</Link>
    </li>
    <li>
      <Link href="/qna">고객지원</Link>
    </li>
    <li>
      <Link href="/info">공지사항</Link>
    </li>
    <li>
      <Link href="/none">제니시수</Link>
    </li>
```

(3) ref 자체는 리액트 생명주기랑은 별개로 동작하기 때문에 React스럽지 않은것 같다는 점
React의 주요 강점 중 하나는 선언형 방식으로 UI를 관리하는 거라고 합니다.
직접적인 DOM 조작은 일반적으로 React 철학에 맞지 않고요.
React는 state와 props를 통해 UI를 자동으로 업데이트 해주는 것을 목표로 합니다.
어쩔 수 없이 직접 DOM을 조작해야 할 상황이 생길 경우 useRef와 useEffect 같은 훅을 사용해 직접적으로 조작하는 것이지만, 가능하면 React 방식에 맞춰 state나 props를 통해 변경하는 게 더 바람직하다고 생각합니다. (틀리지는 않죠)

(4) 전체적인 코드를 보고 드리는 말씀
잘하면 모바일 조건이나 상태값에 따라 CSS나 Figure 태그를 활성화 하는 방식으로 코드를 간소화할 수 있지 않을까요?
(웹과 모바일 JSX 코드 합치기)

2024-10-23 07:57 UTC, ryungom commented on src/components/layout/Header.tsx
> +      if (item.getAttribute('href')?.split('/')[1] === thisPath) {
반대로 제가 납득되었습니다. 말씀대로 수정해보도록 하겠습니다

2024-10-23 21:33 UTC, redcontroller approved these changes
Header 레이아웃 컴포넌트에서 MainGnb를 컴포넌트로 분할 하셨네요! 👍👍
코드리뷰를 해보니, MainGnb를 세부 3가지 컴포넌트로 분할하면 좋겠네요. 🤔
MainGnb 내에서 조건문으로 분기하기 보다는 3개로 분할한 컴포넌트를 필요한 부분에 적용해주는 게 어떨까요? 🤗

2024-10-23 21:33 UTC, redcontroller commented on src/components/MainGnb.tsx
> +  ];
Line 14번으로 뺴서 전역 변수(상수)로 한번만 정의되게 하면 좋을 것 같아요. 🤔
객체의 경우 리렌더링이 되면 새로운 참조 메모리를 할당하게 되서 그렇습니다. 🎈

2024-10-23 21:33 UTC, redcontroller commented on src/components/MainGnb.tsx
> +      );
컴포넌트 폴더 내에서 mainGnb 폴더를 만들고, 컴포넌트 분할을 하는게 좋을 것 같아요.
해당 부분은 MainGnbWeb 또는 GnbWeb 정도로 하면 되겠네요. 👍

2024-10-23 21:33 UTC, redcontroller commented on src/components/MainGnb.tsx
> +      return <ul className="firstGnb mobileView">{mobileArr}</ul>;
이 부분도 위에서와 같이 MainGnbMobile 또는 GnbMobile 정도로 해서 컴포넌트 분할해주면,
더 가독서이 좋아질 것 같아요 🙌

2024-10-23 21:33 UTC, redcontroller commented on src/components/MainGnb.tsx
> +    }
이 부분도 위에서와 같이 MainGnbSignSet 또는 GnbSignSet 정도로 해서 컴포넌트 분할해주면 더 가독서이 좋아질 것 같아요 🙌

2024-10-24 02:51 UTC, ryungom commented on src/components/MainGnb.tsx
> +      );
그렇네요 컴포넌트 분할할거 이왕 더 쪼갤수 있으면 쪼개면 좋겠어요! 좋습니다

2024-10-24 03:46 UTC, ryungom commented on src/components/MainGnb.tsx
> +  ];
헙 요부분은 리팩토링 다시 진행하면서 zustand로 따로 빼둔 부분입니다! 왜 오래된부분이 남아있는거지... useGnbStore.ts 부분을 참고해주세용

2024-10-24 08:18 UTC, redcontroller reviewed
피드백 요청사항 반영된 부분 확인했습니다.
컴포넌트와 CSS 분할까지 손 보셨더군요 ~ 👍
헤더 기능 개발 수고하셨습니다 !
이제 Merge 가시죠 ~ 🚀

2024-10-24 08:18 UTC, redcontroller commented on src/zustand/useGnbWrap.ts
> +}));
zustand를 통해서 헤더에 들어가는 요소를 관리하는 부분 확인했습니다 😊👍

2024-10-24 08:18 UTC, redcontroller commented on src/components/layout/Header.tsx
컴포넌트 분할을 통해서 필요한 기능을 찾아갈 때 좀 더 직관적일 수 있을 것 같아요 😊
피드백 반영해주셔서 감사합니다 ~ 🙌

2024-10-24 08:18 UTC, redcontroller commented on src/components/mainGnb/GnbSignSet.tsx
tailwind CSS를 basic.css로 옮겨두셨군요! 👍
제가 로그인 기능 개발할 때 이런 작업을 안 해뒀었나 싶었습니다 😥
코드를 개선하다 보면 계속 추가 작업을 하게 만드는 부분이 있는 것 같아요 😊

2024-10-24 08:22 UTC, ryungom commented on src/components/layout/Header.tsx
저도 좋은방향 제시해주셔서 넘나 감사드리는것~!ㅎㅎ

2024-10-24 08:23 UTC, ryungom commented on src/components/mainGnb/GnbSignSet.tsx
메인과 헤더, 푸터같은 경우는 글로벌로 스타일 작업을 해두었다보니 살짝 맞추려고 하다보니... 쫌쫌따리 부분이었습니다 😄

2024-10-24 12:48 UTC, merged